### ISSUE TITLE
Support for Emotion (or just css``)

### ISSUE THREAD

**Issue by geekus** [mskelton/tree-sitter-styled#6]
Hi, is there a way to add support for styles in `css` template literal strings in addition to `styled`?

I get syntax highlighting if I rename
```
css`color: #fff`
```
to 
```
styled`color: #fff`
```
so might be an easy fix? ☺️

![Screenshot 2024-02-23 at 12 48 14](https://github.com/mskelton/tree-sitter-styled/assets/6450570/79b93079-ff0d-4eb6-a6c8-37c4ab1788c3)

![Screenshot 2024-02-23 at 12 48 29](https://github.com/mskelton/tree-sitter-styled/assets/6450570/58602d28-6446-4a2e-bbc4-f0f2fa776f3c)

**Comment by mskelton** [comment]
@geekus I opened a PR in nvim-treesitter to add support for this.

https://github.com/nvim-treesitter/nvim-treesitter/pull/6255

Going to close this issue in favor of that PR.

In the meantime, you can add the following to your `ecma/injections.scm` file

```scm
; css`<css>`, keyframes`<css>`
(call_expression
  function: (identifier) @_name
    (#match? @_name "^(css|keyframes)")
  arguments:
    ((template_string) @injection.content
      (#offset! @injection.content 0 1 0 -1)
      (#set! injection.include-children)
      (#set! injection.language "styled")))
```

**Comment by geekus** [comment]
Thanks a lot! 🎉
